### ISSUE TITLE
[ENHANCEMENT] Filter Gym Alerts

### ISSUE THREAD

**Issue by jane0815** [kvangent/PokeAlarm#182]
## Enhancement Description

Filter gym alerts to only receive Alerts for important gyms. 

## Use cases

Right now alerts are send for every gym on the map. It would be great if it was possible to specify wich gyms we want to get alerts for. 

For example i have a gym in range of my home and i hate to see it has changed colors when i open pokemon go and i don't know for how long. So i like to receive an alerts only for this gym when it goes to a different team. Then i could take it back within minutes.

**Comment by kvangent** [comment]
@jane0815 You can already do this - you can limit gyms the same way you limit pokemon. You can provide a distance instead of true/false, or you can place a geofence to limit them.

**Comment by jane0815** [comment]
Sounds like this could work for me! Sorry i missed that option. Will try to upgrade and check it out! :)

**Comment by jane0815** [comment]
I tryed to setup gym alerts with a distance but it did not work as expected.

I had this in my config:

	"gyms":{
		"To_Valor":"False",
		"To_Mystic":"False",
		"To_Instinct":"False",
		"From_Valor":"False",
		"From_Mystic":"100",
		"From_Instinct":"False"
	},

But i still got Alerts for every gym on the map that changed from blue to something else.

**Comment by brettgus** [comment]
@jane0815 Are you using the most recent commit?  I believe it's fixed it was fixed in 2fdb2fc.  If you are all up to date and it isn't working please open a new issue and fill out the issue template

**Comment by jane0815** [comment]
From https://github.com/kvangent/PokeAlarm
   2fdb2fc..1250d62  master     -> origin/master
Updating 2fdb2fc..1250d62

No. Thanks for you fast reply! Will try if it is fixed now! :)

**Comment by kvangent** [comment]
@jane0815 Try running in `--debug` mode and post the output. I don't think that update will solve your problem (but I'm often wrong).

**Comment by jane0815** [comment]
@kvangent You are right. It did not fix the problem. Will run in debug mode later and post log here.

**Comment by kvangent** [comment]
@jane0815 Also before I forget, you need to have a location specified via the command line for this to work (and if its not a Lat and Lng, you'll need an API-Key provided as wel)

**Comment by jane0815** [comment]
@kvangent It seems to be working fine after i set a location and api key! Only get alerts for the gym at my house. :)

Thank you so much!
